import { MigrationInterface, QueryRunner } from "typeorm";

export class RefactorAutoGenPrimaryKeys1759419349370 implements MigrationInterface {
    name = 'RefactorAutoGenPrimaryKeys1759419349370'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "FK_583007013543f31bbce2c15a976"`);
        await queryRunner.query(`ALTER TABLE "parent" DROP CONSTRAINT "PK_bf93c41ee1ae1649869ebd05617"`);
        await queryRunner.query(`ALTER TABLE "parent" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "parent" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "parent" ADD CONSTRAINT "PK_bf93c41ee1ae1649869ebd05617" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "FK_004c0d4b6bc333ba0522ed6215e"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "FK_c25e2e04077caf63fa80e55fcc8"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "PK_f80e086c249b9f3f3ff2fd321b7"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "issue" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "PK_f80e086c249b9f3f3ff2fd321b7" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "issue" DROP COLUMN "instructor_id"`);
        await queryRunner.query(`ALTER TABLE "issue" ADD "instructor_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issue" DROP COLUMN "activity_session_id"`);
        await queryRunner.query(`ALTER TABLE "issue" ADD "activity_session_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "FK_48139306c10b136f8e99513536e"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "FK_18b72a4646c8cd18e3dca0525ca"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "PK_3c452b1f7ee1f2cfcc2e8b1f941"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "PK_18b72a4646c8cd18e3dca0525ca" PRIMARY KEY ("activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP COLUMN "station_id"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD "station_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "PK_18b72a4646c8cd18e3dca0525ca"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "PK_3c452b1f7ee1f2cfcc2e8b1f941" PRIMARY KEY ("activity_session_id", "station_id")`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "PK_3c452b1f7ee1f2cfcc2e8b1f941"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "PK_48139306c10b136f8e99513536e" PRIMARY KEY ("station_id")`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP COLUMN "activity_session_id"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD "activity_session_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "PK_48139306c10b136f8e99513536e"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "PK_3c452b1f7ee1f2cfcc2e8b1f941" PRIMARY KEY ("station_id", "activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_8b35afd38690c8328420a307420"`);
        await queryRunner.query(`ALTER TABLE "station" DROP CONSTRAINT "PK_cad1b3e7182ef8df1057b82f6aa"`);
        await queryRunner.query(`ALTER TABLE "station" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "station" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "station" ADD CONSTRAINT "PK_cad1b3e7182ef8df1057b82f6aa" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_c3b9a250b4ad2797f1b59ac7984"`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_4b06506b41928830009d16a306b"`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_f87d8bec6ad18475aaf1e630411"`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "PK_026602e21388c315b5b4dc17b4b"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "PK_8b35afd38690c8328420a307420" PRIMARY KEY ("station_id")`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP COLUMN "child_id"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD "child_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "PK_8b35afd38690c8328420a307420"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "PK_026602e21388c315b5b4dc17b4b" PRIMARY KEY ("station_id", "child_id")`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "PK_026602e21388c315b5b4dc17b4b"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "PK_c3b9a250b4ad2797f1b59ac7984" PRIMARY KEY ("child_id")`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP COLUMN "station_id"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD "station_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "PK_c3b9a250b4ad2797f1b59ac7984"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "PK_026602e21388c315b5b4dc17b4b" PRIMARY KEY ("child_id", "station_id")`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP COLUMN "instructor_id"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD "instructor_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP COLUMN "activity_session_id"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD "activity_session_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "FK_62c328685da034db02291d6bee9"`);
        await queryRunner.query(`ALTER TABLE "instructor" DROP CONSTRAINT "PK_ccc0348eefb581ca002c05ef2f3"`);
        await queryRunner.query(`ALTER TABLE "instructor" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "instructor" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "instructor" ADD CONSTRAINT "PK_ccc0348eefb581ca002c05ef2f3" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "FK_e2f2a46ae5c260a36fd5674caf0"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "PK_ce4be5546999080c882bcfacf56"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "PK_e2f2a46ae5c260a36fd5674caf0" PRIMARY KEY ("activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP COLUMN "instructor_id"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD "instructor_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "PK_e2f2a46ae5c260a36fd5674caf0"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "PK_ce4be5546999080c882bcfacf56" PRIMARY KEY ("activity_session_id", "instructor_id")`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "PK_ce4be5546999080c882bcfacf56"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "PK_62c328685da034db02291d6bee9" PRIMARY KEY ("instructor_id")`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP COLUMN "activity_session_id"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD "activity_session_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "PK_62c328685da034db02291d6bee9"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "PK_ce4be5546999080c882bcfacf56" PRIMARY KEY ("instructor_id", "activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "FK_37c262056788545ca929955298c"`);
        await queryRunner.query(`ALTER TABLE "activity_session" DROP CONSTRAINT "PK_b1eec88abee31d02a6790463abb"`);
        await queryRunner.query(`ALTER TABLE "activity_session" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "activity_session" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "activity_session" ADD CONSTRAINT "PK_b1eec88abee31d02a6790463abb" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "FK_79dc85c70337d169340f2d53fea"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "PK_b259dbff899f986441575fd3d26"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "PK_37c262056788545ca929955298c" PRIMARY KEY ("activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP COLUMN "child_id"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD "child_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "PK_37c262056788545ca929955298c"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "PK_b259dbff899f986441575fd3d26" PRIMARY KEY ("activity_session_id", "child_id")`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "PK_b259dbff899f986441575fd3d26"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "PK_79dc85c70337d169340f2d53fea" PRIMARY KEY ("child_id")`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP COLUMN "activity_session_id"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD "activity_session_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "PK_79dc85c70337d169340f2d53fea"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "PK_b259dbff899f986441575fd3d26" PRIMARY KEY ("child_id", "activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP CONSTRAINT "FK_7b070ad0050b941833fcb184678"`);
        await queryRunner.query(`ALTER TABLE "health_professional" DROP CONSTRAINT "PK_a64d31c39d2af6daa453ea9f98e"`);
        await queryRunner.query(`ALTER TABLE "health_professional" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "health_professional" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "health_professional" ADD CONSTRAINT "PK_a64d31c39d2af6daa453ea9f98e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP CONSTRAINT "FK_15750768b5712417a550e8ad986"`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP CONSTRAINT "PK_3646662064ed9dbbe82e1efd19f"`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD CONSTRAINT "PK_3646662064ed9dbbe82e1efd19f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP COLUMN "child_id"`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD "child_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP COLUMN "health_professional_id"`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD "health_professional_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "FK_9f61ce787dc165b3185b5f5d47f"`);
        await queryRunner.query(`ALTER TABLE "child" DROP CONSTRAINT "PK_4609b9b323ca37c6bc435ec4b6b"`);
        await queryRunner.query(`ALTER TABLE "child" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "child" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "child" ADD CONSTRAINT "PK_4609b9b323ca37c6bc435ec4b6b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "PK_0b884bd66a60bc2ae117fc0bb09"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "PK_9f61ce787dc165b3185b5f5d47f" PRIMARY KEY ("child_id")`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP COLUMN "parent_id"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD "parent_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "PK_9f61ce787dc165b3185b5f5d47f"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "PK_0b884bd66a60bc2ae117fc0bb09" PRIMARY KEY ("child_id", "parent_id")`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "PK_0b884bd66a60bc2ae117fc0bb09"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "PK_583007013543f31bbce2c15a976" PRIMARY KEY ("parent_id")`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP COLUMN "child_id"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD "child_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "PK_583007013543f31bbce2c15a976"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "PK_0b884bd66a60bc2ae117fc0bb09" PRIMARY KEY ("parent_id", "child_id")`);
        await queryRunner.query(`ALTER TABLE "admin" DROP CONSTRAINT "PK_e032310bcef831fb83101899b10"`);
        await queryRunner.query(`ALTER TABLE "admin" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "admin" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "admin" ADD CONSTRAINT "PK_e032310bcef831fb83101899b10" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "FK_004c0d4b6bc333ba0522ed6215e" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "FK_c25e2e04077caf63fa80e55fcc8" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "FK_48139306c10b136f8e99513536e" FOREIGN KEY ("station_id") REFERENCES "station"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "FK_18b72a4646c8cd18e3dca0525ca" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_c3b9a250b4ad2797f1b59ac7984" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_8b35afd38690c8328420a307420" FOREIGN KEY ("station_id") REFERENCES "station"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_4b06506b41928830009d16a306b" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_f87d8bec6ad18475aaf1e630411" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "FK_62c328685da034db02291d6bee9" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "FK_e2f2a46ae5c260a36fd5674caf0" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "FK_79dc85c70337d169340f2d53fea" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "FK_37c262056788545ca929955298c" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD CONSTRAINT "FK_15750768b5712417a550e8ad986" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD CONSTRAINT "FK_7b070ad0050b941833fcb184678" FOREIGN KEY ("health_professional_id") REFERENCES "health_professional"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "FK_583007013543f31bbce2c15a976" FOREIGN KEY ("parent_id") REFERENCES "parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "FK_9f61ce787dc165b3185b5f5d47f" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "FK_9f61ce787dc165b3185b5f5d47f"`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "FK_583007013543f31bbce2c15a976"`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP CONSTRAINT "FK_7b070ad0050b941833fcb184678"`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP CONSTRAINT "FK_15750768b5712417a550e8ad986"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "FK_37c262056788545ca929955298c"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "FK_79dc85c70337d169340f2d53fea"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "FK_e2f2a46ae5c260a36fd5674caf0"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "FK_62c328685da034db02291d6bee9"`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_f87d8bec6ad18475aaf1e630411"`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_4b06506b41928830009d16a306b"`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_8b35afd38690c8328420a307420"`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_c3b9a250b4ad2797f1b59ac7984"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "FK_18b72a4646c8cd18e3dca0525ca"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "FK_48139306c10b136f8e99513536e"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "FK_c25e2e04077caf63fa80e55fcc8"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "FK_004c0d4b6bc333ba0522ed6215e"`);
        await queryRunner.query(`ALTER TABLE "admin" DROP CONSTRAINT "PK_e032310bcef831fb83101899b10"`);
        await queryRunner.query(`ALTER TABLE "admin" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "admin" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin" ADD CONSTRAINT "PK_e032310bcef831fb83101899b10" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "PK_0b884bd66a60bc2ae117fc0bb09"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "PK_583007013543f31bbce2c15a976" PRIMARY KEY ("parent_id")`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP COLUMN "child_id"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD "child_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "PK_583007013543f31bbce2c15a976"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "PK_0b884bd66a60bc2ae117fc0bb09" PRIMARY KEY ("child_id", "parent_id")`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "PK_0b884bd66a60bc2ae117fc0bb09"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "PK_9f61ce787dc165b3185b5f5d47f" PRIMARY KEY ("child_id")`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP COLUMN "parent_id"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD "parent_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "PK_9f61ce787dc165b3185b5f5d47f"`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "PK_0b884bd66a60bc2ae117fc0bb09" PRIMARY KEY ("parent_id", "child_id")`);
        await queryRunner.query(`ALTER TABLE "child" DROP CONSTRAINT "PK_4609b9b323ca37c6bc435ec4b6b"`);
        await queryRunner.query(`ALTER TABLE "child" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "child" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child" ADD CONSTRAINT "PK_4609b9b323ca37c6bc435ec4b6b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "FK_9f61ce787dc165b3185b5f5d47f" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP COLUMN "health_professional_id"`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD "health_professional_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP COLUMN "child_id"`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD "child_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP CONSTRAINT "PK_3646662064ed9dbbe82e1efd19f"`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD CONSTRAINT "PK_3646662064ed9dbbe82e1efd19f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD CONSTRAINT "FK_15750768b5712417a550e8ad986" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_professional" DROP CONSTRAINT "PK_a64d31c39d2af6daa453ea9f98e"`);
        await queryRunner.query(`ALTER TABLE "health_professional" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "health_professional" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "health_professional" ADD CONSTRAINT "PK_a64d31c39d2af6daa453ea9f98e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD CONSTRAINT "FK_7b070ad0050b941833fcb184678" FOREIGN KEY ("health_professional_id") REFERENCES "health_professional"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "PK_b259dbff899f986441575fd3d26"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "PK_79dc85c70337d169340f2d53fea" PRIMARY KEY ("child_id")`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP COLUMN "activity_session_id"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD "activity_session_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "PK_79dc85c70337d169340f2d53fea"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "PK_b259dbff899f986441575fd3d26" PRIMARY KEY ("activity_session_id", "child_id")`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "PK_b259dbff899f986441575fd3d26"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "PK_37c262056788545ca929955298c" PRIMARY KEY ("activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP COLUMN "child_id"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD "child_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "PK_37c262056788545ca929955298c"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "PK_b259dbff899f986441575fd3d26" PRIMARY KEY ("child_id", "activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "FK_79dc85c70337d169340f2d53fea" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_session" DROP CONSTRAINT "PK_b1eec88abee31d02a6790463abb"`);
        await queryRunner.query(`ALTER TABLE "activity_session" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "activity_session" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activity_session" ADD CONSTRAINT "PK_b1eec88abee31d02a6790463abb" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "FK_37c262056788545ca929955298c" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "PK_ce4be5546999080c882bcfacf56"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "PK_62c328685da034db02291d6bee9" PRIMARY KEY ("instructor_id")`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP COLUMN "activity_session_id"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD "activity_session_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "PK_62c328685da034db02291d6bee9"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "PK_ce4be5546999080c882bcfacf56" PRIMARY KEY ("activity_session_id", "instructor_id")`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "PK_ce4be5546999080c882bcfacf56"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "PK_e2f2a46ae5c260a36fd5674caf0" PRIMARY KEY ("activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP COLUMN "instructor_id"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD "instructor_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "PK_e2f2a46ae5c260a36fd5674caf0"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "PK_ce4be5546999080c882bcfacf56" PRIMARY KEY ("instructor_id", "activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "FK_e2f2a46ae5c260a36fd5674caf0" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instructor" DROP CONSTRAINT "PK_ccc0348eefb581ca002c05ef2f3"`);
        await queryRunner.query(`ALTER TABLE "instructor" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "instructor" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instructor" ADD CONSTRAINT "PK_ccc0348eefb581ca002c05ef2f3" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "FK_62c328685da034db02291d6bee9" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP COLUMN "activity_session_id"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD "activity_session_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP COLUMN "instructor_id"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD "instructor_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "PK_026602e21388c315b5b4dc17b4b"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "PK_c3b9a250b4ad2797f1b59ac7984" PRIMARY KEY ("child_id")`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP COLUMN "station_id"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD "station_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "PK_c3b9a250b4ad2797f1b59ac7984"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "PK_026602e21388c315b5b4dc17b4b" PRIMARY KEY ("station_id", "child_id")`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "PK_026602e21388c315b5b4dc17b4b"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "PK_8b35afd38690c8328420a307420" PRIMARY KEY ("station_id")`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP COLUMN "child_id"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD "child_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "PK_8b35afd38690c8328420a307420"`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "PK_026602e21388c315b5b4dc17b4b" PRIMARY KEY ("child_id", "station_id")`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_f87d8bec6ad18475aaf1e630411" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_4b06506b41928830009d16a306b" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_c3b9a250b4ad2797f1b59ac7984" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "station" DROP CONSTRAINT "PK_cad1b3e7182ef8df1057b82f6aa"`);
        await queryRunner.query(`ALTER TABLE "station" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "station" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "station" ADD CONSTRAINT "PK_cad1b3e7182ef8df1057b82f6aa" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_8b35afd38690c8328420a307420" FOREIGN KEY ("station_id") REFERENCES "station"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "PK_3c452b1f7ee1f2cfcc2e8b1f941"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "PK_48139306c10b136f8e99513536e" PRIMARY KEY ("station_id")`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP COLUMN "activity_session_id"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD "activity_session_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "PK_48139306c10b136f8e99513536e"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "PK_3c452b1f7ee1f2cfcc2e8b1f941" PRIMARY KEY ("activity_session_id", "station_id")`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "PK_3c452b1f7ee1f2cfcc2e8b1f941"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "PK_18b72a4646c8cd18e3dca0525ca" PRIMARY KEY ("activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP COLUMN "station_id"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD "station_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "PK_18b72a4646c8cd18e3dca0525ca"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "PK_3c452b1f7ee1f2cfcc2e8b1f941" PRIMARY KEY ("station_id", "activity_session_id")`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "FK_18b72a4646c8cd18e3dca0525ca" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "FK_48139306c10b136f8e99513536e" FOREIGN KEY ("station_id") REFERENCES "station"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue" DROP COLUMN "activity_session_id"`);
        await queryRunner.query(`ALTER TABLE "issue" ADD "activity_session_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issue" DROP COLUMN "instructor_id"`);
        await queryRunner.query(`ALTER TABLE "issue" ADD "instructor_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "PK_f80e086c249b9f3f3ff2fd321b7"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "issue" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "PK_f80e086c249b9f3f3ff2fd321b7" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "FK_c25e2e04077caf63fa80e55fcc8" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "FK_004c0d4b6bc333ba0522ed6215e" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent" DROP CONSTRAINT "PK_bf93c41ee1ae1649869ebd05617"`);
        await queryRunner.query(`ALTER TABLE "parent" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "parent" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parent" ADD CONSTRAINT "PK_bf93c41ee1ae1649869ebd05617" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "FK_583007013543f31bbce2c15a976" FOREIGN KEY ("parent_id") REFERENCES "parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
