import { MigrationInterface, QueryRunner } from "typeorm";

export class AddMigration1761734441825 implements MigrationInterface {
    name = 'AddMigration1761734441825'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "admin" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying, "profile_picture_url" character varying NOT NULL, "phone" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "activated_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_de87485f6489f5d0995f5841952" UNIQUE ("email"), CONSTRAINT "PK_e032310bcef831fb83101899b10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de87485f6489f5d0995f584195" ON "admin" ("email") `);
        await queryRunner.query(`CREATE TABLE "station_activity_session" ("station_id" uuid NOT NULL, "activity_session_id" uuid NOT NULL, "stop_number" integer NOT NULL, "scheduled_at" TIMESTAMP WITH TIME ZONE NOT NULL, "arrived_at" TIMESTAMP WITH TIME ZONE, "left_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3c452b1f7ee1f2cfcc2e8b1f941" PRIMARY KEY ("station_id", "activity_session_id"))`);
        await queryRunner.query(`CREATE TABLE "route" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "activity_type" character varying NOT NULL, "distance_meters" integer NOT NULL, "bounds_north" double precision NOT NULL, "bounds_east" double precision NOT NULL, "bounds_south" double precision NOT NULL, "bounds_west" double precision NOT NULL, "metadata" jsonb NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_cc16047ba5141ec8dec50451df8" UNIQUE ("name"), CONSTRAINT "CHK_0ca8d8000a3a77fc584b05edf7" CHECK ("activity_type" IN ('pedibus', 'ciclo_expresso')), CONSTRAINT "PK_08affcd076e46415e5821acf52d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "route_station" ("route_id" uuid NOT NULL, "station_id" uuid NOT NULL, "stop_number" integer NOT NULL, "distance_from_start_meters" double precision NOT NULL, "time_from_start_minutes" integer NOT NULL, "distance_from_previous_station_meters" integer NOT NULL, CONSTRAINT "PK_e6da4af38b1a244db8453302186" PRIMARY KEY ("route_id", "station_id"))`);
        await queryRunner.query(`CREATE TABLE "station" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" character varying NOT NULL, "latitude" double precision NOT NULL, "longitude" double precision NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "CHK_e7c2bf9c9e65e3c0b2bd036383" CHECK ("type" IN ('regular', 'school')), CONSTRAINT "PK_cad1b3e7182ef8df1057b82f6aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e281fb092c7316f9a0d1857354" ON "station" ("latitude") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ea929a5934759320d074cd4db" ON "station" ("longitude") `);
        await queryRunner.query(`CREATE TABLE "child_station" ("child_id" uuid NOT NULL, "station_id" uuid NOT NULL, "type" character varying NOT NULL, "instructor_id" uuid NOT NULL, "activity_session_id" uuid NOT NULL, "registered_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_6288dedacb93c8a5deb652e03b" CHECK ("type" IN ('in', 'out')), CONSTRAINT "PK_09af633c742353fe1c05d504e50" PRIMARY KEY ("child_id", "station_id", "type"))`);
        await queryRunner.query(`CREATE TABLE "health_professional" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying, "profile_picture_url" character varying NOT NULL, "phone" character varying NOT NULL, "specialty" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "activated_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_22d25f3882c416e2ad6d5c6ab08" UNIQUE ("email"), CONSTRAINT "CHK_7c3d0d467324d1531ae2f003b2" CHECK ("specialty" IN ('pediatrician', 'nutritionist', 'general_practitioner')), CONSTRAINT "PK_a64d31c39d2af6daa453ea9f98e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22d25f3882c416e2ad6d5c6ab0" ON "health_professional" ("email") `);
        await queryRunner.query(`CREATE TABLE "medical_report" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "child_id" uuid NOT NULL, "health_professional_id" uuid NOT NULL, "diagnosis" text NOT NULL, "recommendations" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3646662064ed9dbbe82e1efd19f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "evaluation1" integer NOT NULL, "evaluation2" integer NOT NULL, "evaluation3" integer NOT NULL, "evaluation4" integer NOT NULL, "evaluation5" integer NOT NULL, "text_feedback" character varying NOT NULL, "overall_rating" integer NOT NULL, "activity_session_id" uuid NOT NULL, "child_id" uuid NOT NULL, "parent_id" uuid NOT NULL, "submited_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8389f9e087a57689cd5be8b2b13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "parent_station" ("parent_id" uuid NOT NULL, "instructor_id" uuid NOT NULL, "activity_session_id" uuid NOT NULL, "registered_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0ec0ec83d30cd18f0aaf1bb53f0" PRIMARY KEY ("parent_id"))`);
        await queryRunner.query(`CREATE TABLE "parent" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying, "profile_picture_url" character varying NOT NULL, "phone" character varying NOT NULL, "address" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "activated_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_9158391af7b8ca4911efaad8a73" UNIQUE ("email"), CONSTRAINT "PK_bf93c41ee1ae1649869ebd05617" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9158391af7b8ca4911efaad8a7" ON "parent" ("email") `);
        await queryRunner.query(`CREATE TABLE "parent_child" ("parent_id" uuid NOT NULL, "child_id" uuid NOT NULL, "associated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0b884bd66a60bc2ae117fc0bb09" PRIMARY KEY ("parent_id", "child_id"))`);
        await queryRunner.query(`CREATE TABLE "child_activity_record" ("child_id" uuid NOT NULL, "activity_session_id" uuid NOT NULL, "distance_meters" integer NOT NULL, "duration_seconds" integer NOT NULL, "calories_burned" integer NOT NULL, CONSTRAINT "PK_c086db3444d54c4ddfac38fa833" PRIMARY KEY ("child_id", "activity_session_id"))`);
        await queryRunner.query(`CREATE TABLE "client_stat" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "distance_meters" integer NOT NULL, "co2_saved" integer NOT NULL, "calories_burned" integer NOT NULL, "points_earned" integer NOT NULL, "activity_date" TIMESTAMP WITH TIME ZONE NOT NULL, "activity_session_id" uuid NOT NULL, "child_id" uuid, CONSTRAINT "PK_42311d46b67da5fc71f32dc3cc3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "child_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "child_id" uuid NOT NULL, "height_centimeters" integer NOT NULL, "weight_kilograms" integer NOT NULL, "age" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b085573ac3f438be52a3810e5ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "child" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "profile_picture_url" character varying NOT NULL, "gender" character varying NOT NULL, "height_centimeters" integer NOT NULL, "weight_kilograms" integer NOT NULL, "school" character varying NOT NULL, "school_grade" integer NOT NULL, "drop_off_station_id" uuid NOT NULL, "date_of_birth" date NOT NULL, "health_problems" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "CHK_3385608ebec1fb7bb29020243c" CHECK ("gender" IN ('male', 'female')), CONSTRAINT "PK_4609b9b323ca37c6bc435ec4b6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "child_activity_session" ("child_id" uuid NOT NULL, "activity_session_id" uuid NOT NULL, "parent_id" uuid NOT NULL, "is_late_registration" boolean NOT NULL, "registered_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "pick_up_station_id" uuid NOT NULL, CONSTRAINT "PK_604103384948cc23645011cbc10" PRIMARY KEY ("child_id", "activity_session_id", "parent_id", "is_late_registration"))`);
        await queryRunner.query(`CREATE TABLE "parent_activity_session" ("parent_id" uuid NOT NULL, "activity_session_id" uuid NOT NULL, "registered_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a7b357c4f5f847068cd3d3e5b60" PRIMARY KEY ("parent_id", "activity_session_id"))`);
        await queryRunner.query(`CREATE TABLE "issue" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" text NOT NULL, "image_ur_ls" character varying array NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE, "resolved_at" TIMESTAMP WITH TIME ZONE, "instructor_id" uuid NOT NULL, "activity_session_id" uuid NOT NULL, CONSTRAINT "PK_f80e086c249b9f3f3ff2fd321b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity_session" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "mode" character varying NOT NULL, "in_late_registration" boolean NOT NULL DEFAULT false, "route_id" uuid NOT NULL, "weather_temperature" integer, "weather_type" character varying, "scheduled_at" TIMESTAMP WITH TIME ZONE NOT NULL, "started_by_id" uuid, "started_at" TIMESTAMP WITH TIME ZONE, "finished_by_id" uuid, "finished_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "CHK_a51c61bc1985457ba5906afca1" CHECK ("weather_type" IN ('thunderstorm', 'drizzle', 'rain', 'snow', 'atmosphere', 'clear', 'clouds')), CONSTRAINT "CHK_7564e7fe2b822aea7f01f7d3b4" CHECK ("mode" IN ('walk', 'bike')), CONSTRAINT "CHK_60459c8424dfa4b118e615488b" CHECK ("type" IN ('pedibus', 'ciclo_expresso')), CONSTRAINT "PK_b1eec88abee31d02a6790463abb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "instructor_activity_session" ("instructor_id" uuid NOT NULL, "activity_session_id" uuid NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ce4be5546999080c882bcfacf56" PRIMARY KEY ("instructor_id", "activity_session_id"))`);
        await queryRunner.query(`CREATE TABLE "instructor" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying, "profile_picture_url" character varying NOT NULL, "phone" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "activated_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_6222960ab4f2b68e84bc00bfeeb" UNIQUE ("email"), CONSTRAINT "PK_ccc0348eefb581ca002c05ef2f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6222960ab4f2b68e84bc00bfee" ON "instructor" ("email") `);
        await queryRunner.query(`CREATE TABLE "user" ("id" character varying NOT NULL, "name" character varying NOT NULL, "profile_picture_url" character varying NOT NULL, "admin_id" uuid, "instructor_id" uuid, "parent_id" uuid, "health_professional_id" uuid, CONSTRAINT "REL_c143511e72fac735b8006051e5" UNIQUE ("admin_id"), CONSTRAINT "REL_11c03fb8b962b9a304677f462f" UNIQUE ("instructor_id"), CONSTRAINT "REL_acb096eef4d8b5acdd7acbb5c8" UNIQUE ("parent_id"), CONSTRAINT "REL_09a75d99124789b3ff569bb9b0" UNIQUE ("health_professional_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "chat_id" uuid NOT NULL, "sender_id" character varying NOT NULL, "sender_name" character varying NOT NULL, CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "chat_name" character varying, "chat_type" character varying NOT NULL, "destinataire_photo" character varying NOT NULL, CONSTRAINT "CHK_da8a040f3fee38a8681e9c969d" CHECK ("chat_type" IN ('group_chat', 'individual_chat')), CONSTRAINT "PK_9d0b2ba74336710fd31154738a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_chat" ("user_id" character varying NOT NULL, "chat_id" uuid NOT NULL, CONSTRAINT "PK_1a0006be82337a8768d40250893" PRIMARY KEY ("user_id", "chat_id"))`);
        await queryRunner.query(`CREATE TABLE "badge" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "image_url" character varying NOT NULL, "criteria" character varying NOT NULL, "valueneeded" integer, CONSTRAINT "UQ_35ed068bad78456ff543323916d" UNIQUE ("name"), CONSTRAINT "CHK_f38312b1d6073aeb048abae24a" CHECK ("criteria" IN ('streak', 'distance', 'calories', 'weather', 'points', 'special', 'leaderboard', 'participation')), CONSTRAINT "PK_76b7011c864d4521a14a5196c49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client_badge" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "parent_id" uuid, "child_id" uuid, "badge_id" uuid NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5c99c874b9c97ca4c30b35f5ea5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "FK_48139306c10b136f8e99513536e" FOREIGN KEY ("station_id") REFERENCES "station"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" ADD CONSTRAINT "FK_18b72a4646c8cd18e3dca0525ca" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_station" ADD CONSTRAINT "FK_3ebd2550b3f583061f276c8569d" FOREIGN KEY ("route_id") REFERENCES "route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_station" ADD CONSTRAINT "FK_d12ae12079d943775d46970d940" FOREIGN KEY ("station_id") REFERENCES "station"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_c3b9a250b4ad2797f1b59ac7984" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_8b35afd38690c8328420a307420" FOREIGN KEY ("station_id") REFERENCES "station"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_4b06506b41928830009d16a306b" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_station" ADD CONSTRAINT "FK_f87d8bec6ad18475aaf1e630411" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD CONSTRAINT "FK_15750768b5712417a550e8ad986" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_report" ADD CONSTRAINT "FK_7b070ad0050b941833fcb184678" FOREIGN KEY ("health_professional_id") REFERENCES "health_professional"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD CONSTRAINT "FK_9f4d758077600e7e6f5ae8d6a52" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD CONSTRAINT "FK_2f83712f5cc35e4d02be7b83471" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD CONSTRAINT "FK_83e404d59c4d53cc7d4df25c506" FOREIGN KEY ("parent_id") REFERENCES "parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_station" ADD CONSTRAINT "FK_0ec0ec83d30cd18f0aaf1bb53f0" FOREIGN KEY ("parent_id") REFERENCES "parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_station" ADD CONSTRAINT "FK_a9e7e99f4bec4c9a33f8f21e61a" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_station" ADD CONSTRAINT "FK_faa105d69140348c91b0f862e99" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "FK_583007013543f31bbce2c15a976" FOREIGN KEY ("parent_id") REFERENCES "parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_child" ADD CONSTRAINT "FK_9f61ce787dc165b3185b5f5d47f" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_activity_record" ADD CONSTRAINT "FK_bd07eb52538d4f09d764557bcb1" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_activity_record" ADD CONSTRAINT "FK_bc028782ef193c5f9b48a1f761e" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_stat" ADD CONSTRAINT "FK_6ecd666a6cd3a1e12c28ee9acd1" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_stat" ADD CONSTRAINT "FK_07c19fc502327873730d894a7b4" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_history" ADD CONSTRAINT "FK_4b5d60b7c0938e0eebaabc002bc" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child" ADD CONSTRAINT "FK_968e30784c5091da17667c3118f" FOREIGN KEY ("drop_off_station_id") REFERENCES "station"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "FK_79dc85c70337d169340f2d53fea" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "FK_37c262056788545ca929955298c" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "FK_449f0b095f3a17f704527eb211f" FOREIGN KEY ("pick_up_station_id") REFERENCES "station"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" ADD CONSTRAINT "FK_1a1cfefc6b46a737805d8026990" FOREIGN KEY ("parent_id") REFERENCES "parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_activity_session" ADD CONSTRAINT "FK_8694de248de861ea28aa90db4c4" FOREIGN KEY ("parent_id") REFERENCES "parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_activity_session" ADD CONSTRAINT "FK_607aaf42631f778872cab70192f" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "FK_004c0d4b6bc333ba0522ed6215e" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "FK_c25e2e04077caf63fa80e55fcc8" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_session" ADD CONSTRAINT "FK_426fd998bca92d995b9d6bd17d7" FOREIGN KEY ("started_by_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_session" ADD CONSTRAINT "FK_468d2b5a4a985934f6e7c5b4f1c" FOREIGN KEY ("finished_by_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_session" ADD CONSTRAINT "FK_248be6cef753d710d6f9b016815" FOREIGN KEY ("route_id") REFERENCES "route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "FK_62c328685da034db02291d6bee9" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" ADD CONSTRAINT "FK_e2f2a46ae5c260a36fd5674caf0" FOREIGN KEY ("activity_session_id") REFERENCES "activity_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c143511e72fac735b8006051e55" FOREIGN KEY ("admin_id") REFERENCES "admin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_11c03fb8b962b9a304677f462f4" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_acb096eef4d8b5acdd7acbb5c84" FOREIGN KEY ("parent_id") REFERENCES "parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_09a75d99124789b3ff569bb9b07" FOREIGN KEY ("health_professional_id") REFERENCES "health_professional"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_859ffc7f95098efb4d84d50c632" FOREIGN KEY ("chat_id") REFERENCES "chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_chat" ADD CONSTRAINT "FK_7633fe1395d0705b301a21cf4d3" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_chat" ADD CONSTRAINT "FK_5366da78c4f08914a33f6e23d51" FOREIGN KEY ("chat_id") REFERENCES "chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_badge" ADD CONSTRAINT "FK_5ee4cf0c549c70ebf7760b988dc" FOREIGN KEY ("parent_id") REFERENCES "parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_badge" ADD CONSTRAINT "FK_9c550215951ea6b5ae5a6a53b63" FOREIGN KEY ("child_id") REFERENCES "child"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_badge" ADD CONSTRAINT "FK_1f45b21716e1847b7b89c4a59bb" FOREIGN KEY ("badge_id") REFERENCES "badge"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "client_badge" DROP CONSTRAINT "FK_1f45b21716e1847b7b89c4a59bb"`);
        await queryRunner.query(`ALTER TABLE "client_badge" DROP CONSTRAINT "FK_9c550215951ea6b5ae5a6a53b63"`);
        await queryRunner.query(`ALTER TABLE "client_badge" DROP CONSTRAINT "FK_5ee4cf0c549c70ebf7760b988dc"`);
        await queryRunner.query(`ALTER TABLE "user_chat" DROP CONSTRAINT "FK_5366da78c4f08914a33f6e23d51"`);
        await queryRunner.query(`ALTER TABLE "user_chat" DROP CONSTRAINT "FK_7633fe1395d0705b301a21cf4d3"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_859ffc7f95098efb4d84d50c632"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_09a75d99124789b3ff569bb9b07"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_acb096eef4d8b5acdd7acbb5c84"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_11c03fb8b962b9a304677f462f4"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c143511e72fac735b8006051e55"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "FK_e2f2a46ae5c260a36fd5674caf0"`);
        await queryRunner.query(`ALTER TABLE "instructor_activity_session" DROP CONSTRAINT "FK_62c328685da034db02291d6bee9"`);
        await queryRunner.query(`ALTER TABLE "activity_session" DROP CONSTRAINT "FK_248be6cef753d710d6f9b016815"`);
        await queryRunner.query(`ALTER TABLE "activity_session" DROP CONSTRAINT "FK_468d2b5a4a985934f6e7c5b4f1c"`);
        await queryRunner.query(`ALTER TABLE "activity_session" DROP CONSTRAINT "FK_426fd998bca92d995b9d6bd17d7"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "FK_c25e2e04077caf63fa80e55fcc8"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "FK_004c0d4b6bc333ba0522ed6215e"`);
        await queryRunner.query(`ALTER TABLE "parent_activity_session" DROP CONSTRAINT "FK_607aaf42631f778872cab70192f"`);
        await queryRunner.query(`ALTER TABLE "parent_activity_session" DROP CONSTRAINT "FK_8694de248de861ea28aa90db4c4"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "FK_1a1cfefc6b46a737805d8026990"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "FK_449f0b095f3a17f704527eb211f"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "FK_37c262056788545ca929955298c"`);
        await queryRunner.query(`ALTER TABLE "child_activity_session" DROP CONSTRAINT "FK_79dc85c70337d169340f2d53fea"`);
        await queryRunner.query(`ALTER TABLE "child" DROP CONSTRAINT "FK_968e30784c5091da17667c3118f"`);
        await queryRunner.query(`ALTER TABLE "child_history" DROP CONSTRAINT "FK_4b5d60b7c0938e0eebaabc002bc"`);
        await queryRunner.query(`ALTER TABLE "client_stat" DROP CONSTRAINT "FK_07c19fc502327873730d894a7b4"`);
        await queryRunner.query(`ALTER TABLE "client_stat" DROP CONSTRAINT "FK_6ecd666a6cd3a1e12c28ee9acd1"`);
        await queryRunner.query(`ALTER TABLE "child_activity_record" DROP CONSTRAINT "FK_bc028782ef193c5f9b48a1f761e"`);
        await queryRunner.query(`ALTER TABLE "child_activity_record" DROP CONSTRAINT "FK_bd07eb52538d4f09d764557bcb1"`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "FK_9f61ce787dc165b3185b5f5d47f"`);
        await queryRunner.query(`ALTER TABLE "parent_child" DROP CONSTRAINT "FK_583007013543f31bbce2c15a976"`);
        await queryRunner.query(`ALTER TABLE "parent_station" DROP CONSTRAINT "FK_faa105d69140348c91b0f862e99"`);
        await queryRunner.query(`ALTER TABLE "parent_station" DROP CONSTRAINT "FK_a9e7e99f4bec4c9a33f8f21e61a"`);
        await queryRunner.query(`ALTER TABLE "parent_station" DROP CONSTRAINT "FK_0ec0ec83d30cd18f0aaf1bb53f0"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP CONSTRAINT "FK_83e404d59c4d53cc7d4df25c506"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP CONSTRAINT "FK_2f83712f5cc35e4d02be7b83471"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP CONSTRAINT "FK_9f4d758077600e7e6f5ae8d6a52"`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP CONSTRAINT "FK_7b070ad0050b941833fcb184678"`);
        await queryRunner.query(`ALTER TABLE "medical_report" DROP CONSTRAINT "FK_15750768b5712417a550e8ad986"`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_f87d8bec6ad18475aaf1e630411"`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_4b06506b41928830009d16a306b"`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_8b35afd38690c8328420a307420"`);
        await queryRunner.query(`ALTER TABLE "child_station" DROP CONSTRAINT "FK_c3b9a250b4ad2797f1b59ac7984"`);
        await queryRunner.query(`ALTER TABLE "route_station" DROP CONSTRAINT "FK_d12ae12079d943775d46970d940"`);
        await queryRunner.query(`ALTER TABLE "route_station" DROP CONSTRAINT "FK_3ebd2550b3f583061f276c8569d"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "FK_18b72a4646c8cd18e3dca0525ca"`);
        await queryRunner.query(`ALTER TABLE "station_activity_session" DROP CONSTRAINT "FK_48139306c10b136f8e99513536e"`);
        await queryRunner.query(`DROP TABLE "client_badge"`);
        await queryRunner.query(`DROP TABLE "badge"`);
        await queryRunner.query(`DROP TABLE "user_chat"`);
        await queryRunner.query(`DROP TABLE "chat"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6222960ab4f2b68e84bc00bfee"`);
        await queryRunner.query(`DROP TABLE "instructor"`);
        await queryRunner.query(`DROP TABLE "instructor_activity_session"`);
        await queryRunner.query(`DROP TABLE "activity_session"`);
        await queryRunner.query(`DROP TABLE "issue"`);
        await queryRunner.query(`DROP TABLE "parent_activity_session"`);
        await queryRunner.query(`DROP TABLE "child_activity_session"`);
        await queryRunner.query(`DROP TABLE "child"`);
        await queryRunner.query(`DROP TABLE "child_history"`);
        await queryRunner.query(`DROP TABLE "client_stat"`);
        await queryRunner.query(`DROP TABLE "child_activity_record"`);
        await queryRunner.query(`DROP TABLE "parent_child"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9158391af7b8ca4911efaad8a7"`);
        await queryRunner.query(`DROP TABLE "parent"`);
        await queryRunner.query(`DROP TABLE "parent_station"`);
        await queryRunner.query(`DROP TABLE "feedback"`);
        await queryRunner.query(`DROP TABLE "medical_report"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22d25f3882c416e2ad6d5c6ab0"`);
        await queryRunner.query(`DROP TABLE "health_professional"`);
        await queryRunner.query(`DROP TABLE "child_station"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ea929a5934759320d074cd4db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e281fb092c7316f9a0d1857354"`);
        await queryRunner.query(`DROP TABLE "station"`);
        await queryRunner.query(`DROP TABLE "route_station"`);
        await queryRunner.query(`DROP TABLE "route"`);
        await queryRunner.query(`DROP TABLE "station_activity_session"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de87485f6489f5d0995f584195"`);
        await queryRunner.query(`DROP TABLE "admin"`);
    }

}
